version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC


# models:
#    - name: claims
#      columns:
#               - name: POLICY_NO
#                 discription: policy no

#              - name: DATE_OF_INTIMATION_HO
#                 discription: imitation date

#              - name: PAR_NONPAR_ULIP_LEVELINCREASING
#                discription: parnonpar
