version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC
            - name: claims

models:
        - name: claims
          columns:
                  - name: POLICY_NO
                  - name: DATE_OF_INTIMATION_HO
                    -type: timestamp
                  - name: LOB
                  - name: Fiscal_year
                  - name: month_ho
                    
               
        - name: sum_amt
          columns:
                  - name: month_ho
                  - name: CLAIM_AMOUNTS
                  - name: Fiscal_year
