version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC

models:
        - name: claims
          columns:
                - name: POLICY_NO 
                  description: this is policy number

                - name: PAR_NONPAR_ULIP_LEVELINCREASING
                  description: parnonpar

                - name:  DATE_OF_INTIMATION_HO
                  description: initation date