version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC

models:
        - name: claims
          columns:
                  - name: POLICY_NO
                  - name: DATE_OF_INTIMATION_HO
                  - name: LOB
                  - name: Fiscal_year
                  - name: month_ho
                  - name: CLAIM_AMOUNT