version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC

models:
        - name: claims
          columns:
                  - name: POLICY_NO
                    meta:
                      metrics:
                        claim_count:
                          type: count
                          sql: POLICY_NO
                  - name: Intimation_Date
                    meta:
                      dimension:
                        time_intervals:
                          - DAY
                          - WEEK
                          - MONTH
                          - QUARTER
                          - YEAR
                  - name: Settlement_Date
                    meta:
                      dimension:
                        time_intervals:
                          - DAY
                          - WEEK
                          - MONTH
                          - QUARTER
                          - YEAR
                  - name: LOB
                  - name: Fiscal_year
                  - name: month_ho
                  - name: month_sd
                  - name: month_name
                  - name: month_name_sd
                  - name: CLAIM_AMOUNT
                    meta:
                      metrics:
                        claim_amount_sum:
                          type: sum
                          sql: CLAIM_AMOUNT/10000000
                          format: 'inr'
                  - name: SERVICING_BRANCH_NAME
                  - name: CHANNEL1
                  - name: EARLYNON_EARLY
                  - name: WRITING_AGENT_STATE_NAME
                  - name: NATURE_OF_BASE_POLICY

        - name: claims1
          meta:
            joins:
              - join: claims
                sql_on: ${claims.Fiscal_year} = ${claims1.Fiscal_year} AND ${claims.CHANNEL1} = ${claims1.CHANNEL1} AND
                        ${claims.EARLYNON_EARLY} = ${claims1.EARLYNON_EARLY} AND ${claims.LOB} = ${claims1.LOB}


          columns:
                  - name: POLICY_NO
                    meta:
                      metrics:
                        claim_count:
                          type: count
                          sql: POLICY_NO
                  - name: Settlement_Date
                    meta:
                      dimension:
                        time_intervals:
                          - DAY
                          - WEEK
                          - MONTH
                          - QUARTER
                          - YEAR
                  - name: CLAIM_AMOUNT
                    meta:
                      metrics:
                        claim_amount_sum:
                          type: sum
                          sql: CLAIM_AMOUNT/10000000
                          format: 'inr'
                  - name: Fiscal_year
                  - name: CHANNEL1
                  - name: EARLYNON_EARLY
                  - name: WRITING_AGENT_STATE_NAME
                  - name: LOB

