version: 2

sources:

  - name: DB_01
    database: DB_01
    schema: PUBLIC
    tables:
            - name: CLAIMSDEC
            - name: claims

models:
        - name: claims
          columns:
                  - name: POLICY_NO
                    meta:
                      metrics:
                        policy_no_count:
                          type: count_distinct
                          sql: POLICY_NO
                  - name: Intimation_Date
                    meta:
                      dimension:
                        time_intervals:
                          - DAY
                          - MONTH
                          - QUARTER
                  - name: REPUDIATION_DATE_SETTLEMENT_DATE
                  - name: LOB
                  - name: Fiscal_year
                  - name: month_ho
                  - name: month_sd
                  - name: month_name
                  - name: month_name_sd
                  - name: CLAIM_AMOUNT
                    meta:
                      metrics:
                        claim_amount_sum:
                          type: sum
                          sql: CLAIM_AMOUNT/10000000
                  - name: SERVICING_BRANCH_NAME
                  
